## // autostart your favorite applications here // ##

  exec-once = qs -c noctalia-shell &
  exec-once = bash -c wl-paste --watch cliphist store &  # optional: clipboard history | cliphist is needed
