## // configure your input devices here | https://mangowm.github.io/docs/configuration/input // ##

xkb_rules_layout=br  ## set your keyboard layout here


    ## mouse
  ## accel_profile = 1  ## disable pointer acceleration
  ## accel_speed = 0.2  ## adjust pointer acceleration speed
