
      # // https://mangowm.github.io/docs/configuration/miscellaneous // #

allow_tearing = 2  # // some gpus may need `WLR_DRM_NO_ATOMIC=1` environment variable
 # syncobj_enable = 1  # // in case your games are lagging or stuttering, try enabling this
 # xwayland-persistence = 1

drag_tile_to_tile = 1
