# // window/tag/layer rules | https://mangowm.github.io/docs/window-management/rules // #

layerrule = noanim:1, noblur:1, layer_name:selection  # so you don't get weird blur while taking screenshots
