
auto-reload = true

show-bar = false
show-titles = true

keymap.rmlvo = { layout = "br" }

on-graphics-initialized = [
    { type = "exec", exec = ["vibepanel"] },
    { type = "exec", exec = ["vicinae", "server"] },
    { type = "exec", exec = ["steam", "-silent"] },
    { type = "exec", exec = ["vesktop"] },
    { type = "exec", exec = ["solaar"] },

]

[theme]
bg-color = "#1e1e2e"
border-color = "#313244"
focused-title-bg-color = "#89b4fa"
focused-title-text-color = "#1e1e2e"
unfocused-title-bg-color = "#313244"
unfocused-title-text-color = "#cdd6f4"
attention-requested-bg-color = "#f38ba8"
highlight-color = "#f5c2e7"

[theme]
border-width = 4
title-height = 24
bar-height = 28

[[outputs]]
match.serial-number = "TBLMTF008163"
x = 0
y = 0
scale = 1
mode = {
  width = 2560,
  height = 1440,
  refresh-rate = 179.999
}
vrr { mode = "always", cursor-hz = 90 }
tearing.mode = "variant2"
color-space = "bt2020"
transfer-function = "pq"
blend-space = "linear"

[[outputs]]
name "left"
match.serial-number = "4333F94"
x = 2560
y = 0
scale = 1
mode = {
  width = 2560,
  height = 1440,
  refresh-rate = 179.845
}
color-space = "bt2020"
transfer-function = "pq"
blend-space = "linear"

[[inputs]]
match.name = "Logitech PRO X 2"
accel-profile = "Flat"
accel-speed = 0.0

[color-management]
enabled = true

[env]
ELECTRON_OZONE_PLATFORM_HINT = "wayland"
QT_QPA_PLATFORM = "wayland"
SDL_VIDEODRIVER = "wayland"
CLUTTER_BACKEND = "wayland"
ELM_DISPLAY = "1"

_JAVA_AWT_WM_NONREPARENTING = "1"
AMD_VULKAN_ICD = "RADV"
MESA_SHADER_CACHE_MAX_SIZE = "12G"
PROTON_ENABLE_WAYLAND = "1"
PROTON_DXVK_LOWLATENCY = "1"
DXVK_FRAME_RATE = "177"
DXVK_FRAME_PACE = "low-latency-vrr-180"
WINEDLLOVERRIDES = "dxgi,d3d11,d3d10core,dinput8,ddraw=n,b"
PROTON_LOCAL_SHADER_CACHE = "1"

QT_QPA_PLATFORMTHEME = "qt6ct"
QT_QPA_PLATFORMTHEME_QT6 = "qt6ct"

[shortcuts]
logo-h = "focus-left"
logo-j = "focus-down"
logo-k = "focus-up"
logo-l = "focus-right"

logo-shift-h = "move-left"
logo-shift-j = "move-down"
logo-shift-k = "move-up"
logo-shift-l = "move-right"

logo-d = "split-horizontal"
logo-v = "split-vertical"

logo-shift-t = "toggle-split"
logo-m = "toggle-mono"
logo-f = "toggle-fullscreen"

logo-f = "focus-parent"
logo-c = "open-control-center"
logo-q = "close"
logo-shift-f = "toggle-floating"
logo-t = { type = "exec", exec = "alacritty" }
logo-e = { type = "exec", exec = "dolphin" }
logo-a = { type = "exec", exec = ["vicinae", "toggle"] }
logo-shift-e = "quit"
logo-shift-r = "reload-config-toml"

logo-alt-F1 = { type = "switch-to-vt", num = 1 }
logo-alt-F2 = { type = "switch-to-vt", num = 2 }
logo-alt-F3 = { type = "switch-to-vt", num = 3 }
logo-alt-F4 = { type = "switch-to-vt", num = 4 }
logo-alt-F5 = { type = "switch-to-vt", num = 5 }
logo-alt-F6 = { type = "switch-to-vt", num = 6 }
logo-alt-F7 = { type = "switch-to-vt", num = 7 }
logo-alt-F8 = { type = "switch-to-vt", num = 8 }
logo-alt-F9 = { type = "switch-to-vt", num = 9 }
logo-alt-F10 = { type = "switch-to-vt", num = 10 }
logo-alt-F11 = { type = "switch-to-vt", num = 11 }
logo-alt-F12 = { type = "switch-to-vt", num = 12 }

logo-1 = { type = "show-workspace", name = "1" }
logo-2 = { type = "show-workspace", name = "2" }
logo-3 = { type = "show-workspace", name = "3" }
logo-4 = { type = "show-workspace", name = "4" }
logo-5 = { type = "show-workspace", name = "5" }
logo-6 = { type = "show-workspace", name = "6" }
logo-7 = { type = "show-workspace", name = "7" }
logo-8 = { type = "show-workspace", name = "8" }
logo-9 = { type = "show-workspace", name = "9" }
logo-10 = { type = "show-workspace", name = "10" }
logo-11 = { type = "show-workspace", name = "11" }
logo-12 = { type = "show-workspace", name = "12" }

logo-shift-1 = { type = "move-to-workspace", name = "1" }
logo-shift-2 = { type = "move-to-workspace", name = "2" }
logo-shift-3 = { type = "move-to-workspace", name = "3" }
logo-shift-4 = { type = "move-to-workspace", name = "4" }
logo-shift-5 = { type = "move-to-workspace", name = "5" }
logo-shift-6 = { type = "move-to-workspace", name = "6" }
logo-shift-7 = { type = "move-to-workspace", name = "7" }
logo-shift-8 = { type = "move-to-workspace", name = "8" }
logo-shift-9 = { type = "move-to-workspace", name = "9" }
logo-shift-10 = { type = "move-to-workspace", name = "10" }
logo-shift-11 = { type = "move-to-workspace", name = "11" }
logo-shift-12 = { type = "move-to-workspace", name = "12" }
