# proton config
PROTON_USE_WAYLAND=1
PROTON_USE_WOW64=1
PROTON_DXVK_LOWLATENCY=1

# dxvk config
DXVK_FRAME_PACE=low-latency-vrr-163
DXVK_FRAME_RATE=163

# vkd3d config
VKD3D_FRAME_RATE=163
PROTON_VKD3D_LOWLATENCY=1
VKD3D_CONFIG=descriptor_heap
VKD3D_SWAPCHAIN_PRESENT_MODE=FIFO

# mesa config
ENABLE_LAYER_MESA_ANTI_LAG=1
MESA_SHADER_CACHE_MAX_SIZE=12G
RADV_EXPERIMENTAL=heap

# logs
# PROTON_LOG=+waylanddrv
# WAYLAND_DEBUG=1
